### ISSUE TITLE
serve,serve-base....command not found

### ISSUE THREAD

**Issue by hehanlin** [iMarlboro/SimfaseDevEnv#1]
vagrant ssh
Welcome to Ubuntu 14.04.4 LTS (GNU/Linux 3.13.0-83-generic x86_64)
- Documentation:  https://help.ubuntu.com/
  
  System information as of Mon Apr 25 17:53:22 CST 2016
  
  System load:  0.18              Processes:           98
  Usage of /:   7.7% of 39.34GB   Users logged in:     0
  Memory usage: 18%               IP address for eth0: 10.0.2.15
  Swap usage:   0%                IP address for eth1: 192.168.8.8
  
  Graph this data and manage this system at:
    https://landscape.canonical.com/
  
  Get cloud support with Ubuntu Advantage Cloud Guest:
    http://www.ubuntu.com/business/services/cloud

Last login: Mon Apr 25 17:53:22 2016 from 10.0.2.2
: command not found
: command not found
: command not found
: command not found
-bash: /home/vagrant/.bash_aliases: line 11: syntax error near unexpected token                                                                                                               `$'{\r''
'bash: /home/vagrant/.bash_aliases: line 11:`function create-mysql() {
vagrant@Simfase:~$

//  qq:  972138301   email;   china.hehanlin@gmail.com

**Comment by hehanlin** [comment]
已找到问题，是 换行符不同的问题，用 dos2unix命令 把文件的换行符 换成 unix的就好了

具体操作：

cd 安装目录

find . -type f | xargs dos2unix

**Comment by iMarlboro** [comment]
出现这个问题的原因可能是
你本地的git安装时候，选择了 当git clone到本地后 自动将 换行符 转换成win风格。导致在vagrant中就会出现问题。  根本解决的方法是，下载比较新的git，重新覆盖安装，安装是到换行符步骤是，选择  不去强制修改换行符。

**Comment by hehanlin** [comment]
问题已解决，谢谢
